--------------------------------------------------------
-- Archivo creado  - domingo-junio-04-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence IINSERTAR_SEQUE
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."IINSERTAR_SEQUE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 261 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DETALLEP
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_DETALLEP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_DETALLEV
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_DETALLEV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ESCOGIDO
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_ESCOGIDO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_REGCAFE
--------------------------------------------------------

   CREATE SEQUENCE  "PROYECTO"."SEQ_ID_REGCAFE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMINS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."ADMINS" 
   (	"CEDULA" VARCHAR2(11 BYTE), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"NOMBRE2" VARCHAR2(10 BYTE), 
	"APELLIDO" VARCHAR2(10 BYTE), 
	"APELLIDO2" VARCHAR2(10 BYTE), 
	"CONTRASEÑA" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table CAFES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."CAFES" 
   (	"ID_CAFE" VARCHAR2(2 BYTE), 
	"NOMBRE_CAFE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table DETALLE_FACTURA_VENTAS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."DETALLE_FACTURA_VENTAS" 
   (	"ID_DETALLE_VENTA" VARCHAR2(3 BYTE), 
	"CEDULA_ADMIN" VARCHAR2(11 BYTE), 
	"ID_VENTA" VARCHAR2(3 BYTE), 
	"ID_CAFE" VARCHAR2(2 BYTE), 
	"ID_TIPOC" VARCHAR2(2 BYTE), 
	"FACTOR" VARCHAR2(10 BYTE), 
	"KILOS_NETOS" NUMBER(8,3), 
	"VALOR_KILO" NUMBER(10,2), 
	"VALOR_BASEKILO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table DETALLE_PEDIDOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."DETALLE_PEDIDOS" 
   (	"ID_DETALLE_PEDIDO" VARCHAR2(3 BYTE), 
	"ID_PEDIDO" VARCHAR2(3 BYTE), 
	"ID_PRODUCTO" VARCHAR2(2 BYTE), 
	"CEDULA_EMPLEADO" VARCHAR2(11 BYTE), 
	"CANTIDAD" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."EMPLEADOS" 
   (	"CEDULA_ADMIN" VARCHAR2(11 BYTE), 
	"CEDULA" VARCHAR2(11 BYTE), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"NOMBRE2" VARCHAR2(10 BYTE), 
	"APELLIDO" VARCHAR2(10 BYTE), 
	"APELLIDO2" VARCHAR2(10 BYTE), 
	"FECHA_INICIO" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table FACTURA_PEDIDOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."FACTURA_PEDIDOS" 
   (	"ID_PEDIDO" VARCHAR2(3 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(20 BYTE), 
	"NOMBRE_EMPLEADO" VARCHAR2(10 BYTE), 
	"APELLIDO_EMPLEADO" VARCHAR2(10 BYTE), 
	"TOTAL" NUMBER(10,2), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table FACTURA_VENTAS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."FACTURA_VENTAS" 
   (	"ID_VENTA" VARCHAR2(3 BYTE), 
	"NOMBRE_EMPRESA" VARCHAR2(20 BYTE), 
	"NOMBRE_JEFE" VARCHAR2(10 BYTE), 
	"APELLIDO_JEFE" VARCHAR2(10 BYTE), 
	"GRANO_CAFE" VARCHAR2(15 BYTE), 
	"TIPO_CAFE" VARCHAR2(15 BYTE), 
	"SUBTOTAL" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table NOMINAS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."NOMINAS" 
   (	"ID_NOMINA" VARCHAR2(3 BYTE), 
	"CEDULA_EMPLEADO" VARCHAR2(11 BYTE), 
	"CEDULA_ADMIN" VARCHAR2(11 BYTE), 
	"NOMBRE" VARCHAR2(10 BYTE), 
	"APELLIDO" VARCHAR2(10 BYTE), 
	"TOTAL_KILOS" NUMBER(8,3), 
	"TOTAL_PEDIDOS" NUMBER(6,0) DEFAULT NULL, 
	"SALARIO_BASE" NUMBER(10,2), 
	"TOTAL_PAGAR" NUMBER(10,2), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."PRODUCTOS" 
   (	"ID_PRODUCTO" VARCHAR2(2 BYTE), 
	"NOMBRE_PRODUCTO" VARCHAR2(15 BYTE), 
	"PRECIO_PRODUCTO" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table REGCAFES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."REGCAFES" 
   (	"ID_RCAFE" VARCHAR2(3 BYTE), 
	"CEDULA_ADMIN" VARCHAR2(11 BYTE), 
	"CEREZA_KILOS" NUMBER(8,3), 
	"SECOS_KILOS" NUMBER(8,3), 
	"FECHA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table REGESCOGIDOS
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."REGESCOGIDOS" 
   (	"ID_ESCOGIDO" VARCHAR2(3 BYTE), 
	"CEDULA_ADMIN" VARCHAR2(11 BYTE), 
	"CEDULA_EMPLEADO" VARCHAR2(11 BYTE), 
	"CANTIDAD" VARCHAR2(3 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Table TIPOS_CAFES
--------------------------------------------------------

  CREATE TABLE "PROYECTO"."TIPOS_CAFES" 
   (	"ID_CAFE" VARCHAR2(2 BYTE), 
	"ID_TIPOCAFE" VARCHAR2(2 BYTE), 
	"NOMBRE_TIPOCAFE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
REM INSERTING into PROYECTO.ADMINS
SET DEFINE OFF;
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('1003','Jesus','David','De La Hoz','Peña','313');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('49742284','Dulis','Ines','Fuentes','Montero','192004');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('10','kadir','eduardo','quintero','acosta','12345');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('20','juan','david','peralta','fuentes','12345');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('30','manuel',null,'legro',null,'12345');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('40','wilkar','daniel','ortiz','colpas','12345');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('50','kendrys',null,'diaz',null,'12345');
Insert into PROYECTO.ADMINS (CEDULA,NOMBRE,NOMBRE2,APELLIDO,APELLIDO2,"CONTRASEÑA") values ('225','martina',null,'de la hoz',null,'12345');
REM INSERTING into PROYECTO.CAFES
SET DEFINE OFF;
Insert into PROYECTO.CAFES (ID_CAFE,NOMBRE_CAFE) values ('1','arabica');
Insert into PROYECTO.CAFES (ID_CAFE,NOMBRE_CAFE) values ('2','robusta');
Insert into PROYECTO.CAFES (ID_CAFE,NOMBRE_CAFE) values ('3','liberica');
REM INSERTING into PROYECTO.DETALLE_FACTURA_VENTAS
SET DEFINE OFF;
REM INSERTING into PROYECTO.DETALLE_PEDIDOS
SET DEFINE OFF;
REM INSERTING into PROYECTO.EMPLEADOS
SET DEFINE OFF;
REM INSERTING into PROYECTO.FACTURA_PEDIDOS
SET DEFINE OFF;
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('211',null,null,null,null,to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('298',null,null,null,null,to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('288','dedito','Jesus','David','3000',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('377','empanada','j','j','15000',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('263',null,null,null,null,to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('321',null,null,null,null,to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('888','empanada','5','3','1000',to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('1','empanada','fulano','salcedo','3000',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('2','arepa','fulano','salcedo','2400',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('3',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('4',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('5',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('6',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('7',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('8',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('9',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('10',null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('11',null,null,null,null,to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('999',null,null,null,null,to_date('07/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('255',null,null,null,null,to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('256',null,null,null,null,to_date('07/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('666','empanada','5','3','1000',to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_PEDIDOS (ID_PEDIDO,NOMBRE_PRODUCTO,NOMBRE_EMPLEADO,APELLIDO_EMPLEADO,TOTAL,FECHA) values ('267','empanada','Jesus','David','5000',to_date('03/06/2023','DD/MM/YYYY'));
REM INSERTING into PROYECTO.FACTURA_VENTAS
SET DEFINE OFF;
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('888','lote',null,null,null,null,null,null,to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('226','Marti',null,null,null,null,null,null,to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('828','Telcel','Jesus','De La Hoz','arabica','caturra','897000','897000',to_date('14/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('20','cafi costa','kadir','quintero','arabica','caturra','24000','24000',to_date('02/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('1','cafe_express','juan','peralta','arabica','caturra','40000','40000',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('2','cafe_natural','kadir','quintero','arabica','catuai','20000','20000',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('3','cafe_rusco','kadir','quintero','arabica','caturra','414000','414000',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('4','cafe_rusco',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('5','cafe_express',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('6','cafe_rusco',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('7','cafe_natural',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('8','cafe_natural',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('9','cafe_natural',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('10','cafe_express',null,null,null,null,null,null,to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('19','cafi costa',null,null,null,null,null,null,to_date('02/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('999','ColGatel','Jesus','De La Hoz','arabica','caturra','1089','1089',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.FACTURA_VENTAS (ID_VENTA,NOMBRE_EMPRESA,NOMBRE_JEFE,APELLIDO_JEFE,GRANO_CAFE,TIPO_CAFE,SUBTOTAL,TOTAL,FECHA) values ('88','loco','Jesus','De La Hoz','robusta','pachecolis','15000','15000',to_date('04/06/2023','DD/MM/YYYY'));
REM INSERTING into PROYECTO.NOMINAS
SET DEFINE OFF;
REM INSERTING into PROYECTO.PRODUCTOS
SET DEFINE OFF;
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('1','empanada','1000');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('2','dedito','1000');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('3','arepa','1200');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('4','papa','1500');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('5','arroz','2000');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('6','gaseosa','2500');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('7','poni','2000');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('8','patacon','2500');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('9','speedmax','1700');
Insert into PROYECTO.PRODUCTOS (ID_PRODUCTO,NOMBRE_PRODUCTO,PRECIO_PRODUCTO) values ('10','monster','1800');
REM INSERTING into PROYECTO.REGCAFES
SET DEFINE OFF;
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('61','1003','33','22',to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('82','1003','5','2',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('102','1003','22','23',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('104','1003','3','2',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('107','1003','22','33',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('109','1003','11','22',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('112','1003','5','2',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('113','1003','20','40',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('41','1003','34','32',to_date('03/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('103','1003','2','11',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('105','1003','2','99',to_date('04/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('28','10','20,3','18,2',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('29','20','12,2','10,2',to_date('01/06/2023','DD/MM/YYYY'));
Insert into PROYECTO.REGCAFES (ID_RCAFE,CEDULA_ADMIN,CEREZA_KILOS,SECOS_KILOS,FECHA) values ('81','1003','3','15',to_date('04/06/2023','DD/MM/YYYY'));
REM INSERTING into PROYECTO.REGESCOGIDOS
SET DEFINE OFF;
REM INSERTING into PROYECTO.TIPOS_CAFES
SET DEFINE OFF;
Insert into PROYECTO.TIPOS_CAFES (ID_CAFE,ID_TIPOCAFE,NOMBRE_TIPOCAFE) values ('1','1','caturra');
Insert into PROYECTO.TIPOS_CAFES (ID_CAFE,ID_TIPOCAFE,NOMBRE_TIPOCAFE) values ('1','2','catuai');
Insert into PROYECTO.TIPOS_CAFES (ID_CAFE,ID_TIPOCAFE,NOMBRE_TIPOCAFE) values ('1','3','pache');
Insert into PROYECTO.TIPOS_CAFES (ID_CAFE,ID_TIPOCAFE,NOMBRE_TIPOCAFE) values ('1','4','pachecolis');
Insert into PROYECTO.TIPOS_CAFES (ID_CAFE,ID_TIPOCAFE,NOMBRE_TIPOCAFE) values ('1','5','bourbon');
Insert into PROYECTO.TIPOS_CAFES (ID_CAFE,ID_TIPOCAFE,NOMBRE_TIPOCAFE) values ('1','6','pacamara');
--------------------------------------------------------
--  DDL for Index PK_ADMINS_CEDULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_ADMINS_CEDULA" ON "PROYECTO"."ADMINS" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCTOS_ID_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_PRODUCTOS_ID_PRODUCTO" ON "PROYECTO"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index UK_DETALLE_FACTURA_VENTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."UK_DETALLE_FACTURA_VENTAS" ON "PROYECTO"."DETALLE_FACTURA_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_VENTAS_ID_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_VENTAS_ID_VENTA" ON "PROYECTO"."FACTURA_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_CAFES_ID_CAFE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_CAFES_ID_CAFE" ON "PROYECTO"."CAFES" ("ID_CAFE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLEADOS_CEDULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_EMPLEADOS_CEDULA" ON "PROYECTO"."EMPLEADOS" ("CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_PEDIDOS_ID_PEDIDO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_PEDIDOS_ID_PEDIDO" ON "PROYECTO"."FACTURA_PEDIDOS" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_TIPOS_CAFES_ID_TIPOCAFE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_TIPOS_CAFES_ID_TIPOCAFE" ON "PROYECTO"."TIPOS_CAFES" ("ID_TIPOCAFE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_NOMINAS_ID_NOMINA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_NOMINAS_ID_NOMINA" ON "PROYECTO"."NOMINAS" ("ID_NOMINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Index PK_CAFES_ID_RCAFE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROYECTO"."PK_CAFES_ID_RCAFE" ON "PROYECTO"."REGCAFES" ("ID_RCAFE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO" ;
--------------------------------------------------------
--  DDL for Trigger INSERTAR_ID_NOMINA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."INSERTAR_ID_NOMINA" 
BEFORE INSERT ON NOMINAS
FOR EACH ROW
DECLARE 
BEGIN
SELECT  iinsertar_seque.NEXTVAL INTO :NEW.id_nomina FROM DUAL;
END;

/
ALTER TRIGGER "PROYECTO"."INSERTAR_ID_NOMINA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_FACTURAP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."INSERT_FACTURAP" 
AFTER INSERT ON DETALLE_PEDIDOS
FOR EACH ROW
DECLARE
    nombreE EMPLEADOS.nombre%TYPE;
    apellidoE EMPLEADOS.apellido%TYPE;
    nombreP PRODUCTOS.nombre_producto%TYPE;
    precioP PRODUCTOS.precio_producto%TYPE;
    totalP FACTURA_PEDIDOS.total%TYPE;
BEGIN
    SELECT precio_producto INTO precioP FROM PRODUCTOS WHERE id_producto = :NEW.id_producto;
    totalP := precioP * :NEW.cantidad;
    SELECT nombre, apellido INTO nombreE, apellidoE FROM EMPLEADOS WHERE cedula = :NEW.cedula_empleado;
    SELECT nombre_producto INTO nombreP FROM PRODUCTOS WHERE id_producto = :NEW.id_producto;

    UPDATE FACTURA_PEDIDOS SET total = totalP, nombre_empleado = nombreE, apellido_empleado = apellidoE, nombre_producto = nombreP 
    WHERE id_pedido = :NEW.id_pedido;
END;

/
ALTER TRIGGER "PROYECTO"."INSERT_FACTURAP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERT_FACTURAV
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."INSERT_FACTURAV" 
AFTER INSERT ON DETALLE_FACTURA_VENTAS 
FOR EACH ROW
DECLARE
totalV FACTURA_VENTAS.total%TYPE;
subtotalV FACTURA_VENTAS.subtotal%TYPE;
nombreJ ADMINS.nombre%TYPE;
apellidoJ ADMINS.apellido%TYPE;
nombreTC TIPOS_CAFES.nombre_tipocafe%TYPE;
nombreC CAFES.nombre_cafe%TYPE;
BEGIN
    SELECT nombre, apellido INTO nombreJ, apellidoJ FROM ADMINS WHERE cedula = :NEW.cedula_admin;
    SELECT nombre_tipocafe INTO nombreTC FROM TIPOS_CAFES WHERE id_tipocafe = :NEW.id_tipoC;
    SELECT nombre_cafe INTO nombreC FROM CAFES WHERE id_cafe = :NEW.id_cafe;

    totalV :=  :NEW.KILOS_NETOS  * :NEW.VALOR_KILO;
    subtotalV := :NEW.KILOS_NETOS  * :NEW.VALOR_KILO;

    UPDATE FACTURA_VENTAS
    SET nombre_jefe = nombreJ, apellido_jefe = apellidoJ, grano_cafe = nombreC, tipo_cafe = nombreTC, total = totalV, subtotal = subtotalV
    WHERE id_venta = :NEW.id_venta;
END;

/
ALTER TRIGGER "PROYECTO"."INSERT_FACTURAV" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ID_DETALLEP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."TRIGGER_ID_DETALLEP" 
BEFORE INSERT ON DETALLE_PEDIDOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT seq_id_detalleP.NEXTVAL INTO :NEW.id_detalle_pedido FROM DUAL;
END;

/
ALTER TRIGGER "PROYECTO"."TRIGGER_ID_DETALLEP" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ID_DETALLEV
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."TRIGGER_ID_DETALLEV" 
BEFORE INSERT ON DETALLE_FACTURA_VENTAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT seq_id_detalleV.NEXTVAL INTO :NEW.id_detalle_venta FROM DUAL;
END;

/
ALTER TRIGGER "PROYECTO"."TRIGGER_ID_DETALLEV" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ID_ESCOGIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."TRIGGER_ID_ESCOGIDO" 
BEFORE INSERT ON REGESCOGIDOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT seq_id_escogido.NEXTVAL 
    INTO :NEW.id_escogido 
    FROM DUAL;
END;

/
ALTER TRIGGER "PROYECTO"."TRIGGER_ID_ESCOGIDO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_ID_REGCAFE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PROYECTO"."TRIGGER_ID_REGCAFE" 
BEFORE INSERT ON REGCAFES
FOR EACH ROW
DECLARE
BEGIN
    SELECT  seq_id_regcafe.NEXTVAL 
    INTO :NEW.id_rcafe  
    FROM DUAL;
END;

/
ALTER TRIGGER "PROYECTO"."TRIGGER_ID_REGCAFE" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."ELIMINAR_EMPLEADO" (E_cedula EMPLEADOS.cedula%TYPE)
IS
BEGIN
    DELETE 
    FROM EMPLEADOS
    WHERE  EMPLEADOS.cedula = E_cedula;
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_ADMINISTRADOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_ADMINISTRADOR" (A_cedula ADMINS.cedula%TYPE,
A_nombre ADMINS.nombre%TYPE,
A_nombre2 ADMINS.nombre2%TYPE,
A_apellido ADMINS.apellido%TYPE,
A_apellido2 ADMINS.apellido2%TYPE,
A_contraseña ADMINS.contraseña%TYPE)
IS
BEGIN
    INSERT INTO ADMINS(cedula, nombre, nombre2, apellido, apellido2, contraseña) 
    VALUES (A_cedula, A_nombre, A_nombre2, A_apellido, A_apellido2, A_contraseña);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_DETALLEP
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_DETALLEP" (DP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
DP_id_producto PRODUCTOS.id_producto%TYPE,
DP_cedula_empleado EMPLEADOS.cedula%TYPE,
DP_cantidad DETALLE_PEDIDOS.cantidad%TYPE)
IS
BEGIN
    INSERT INTO DETALLE_PEDIDOS(id_pedido, id_producto, cedula_empleado, cantidad) 
    VALUES (DP_id_pedido, DP_id_producto, DP_cedula_empleado, DP_cantidad);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_DETALLEV
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_DETALLEV" (DFV_cedula_admin DETALLE_FACTURA_VENTAS.cedula_admin%TYPE,
DFV_id_venta DETALLE_FACTURA_VENTAS.id_venta%TYPE,
DFV_id_cafe DETALLE_FACTURA_VENTAS.id_cafe%TYPE,
DFV_id_tipoC DETALLE_FACTURA_VENTAS.id_tipoC%TYPE,
DFV_factor DETALLE_FACTURA_VENTAS.factor%TYPE,
DFV_kilos_netos DETALLE_FACTURA_VENTAS.kilos_netos%TYPE,
DFV_valor_Kilo DETALLE_FACTURA_VENTAS.valor_Kilo%TYPE,
DFV_valor_baseKilo DETALLE_FACTURA_VENTAS.valor_baseKilo%TYPE)
IS
BEGIN
    INSERT INTO DETALLE_FACTURA_VENTAS(cedula_admin, id_venta,id_cafe, id_tipoC, factor, kilos_netos, valor_Kilo, valor_baseKilo) 
    VALUES (DFV_cedula_admin, DFV_id_venta, DFV_id_cafe, DFV_id_tipoC, DFV_factor, DFV_kilos_netos, DFV_valor_Kilo, DFV_valor_baseKilo);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_EMPLEADO" (E_cedula_A ADMINS.cedula%TYPE,
E_cedula EMPLEADOS.cedula%TYPE,
E_nombre EMPLEADOS.nombre%TYPE,
E_nombre2 EMPLEADOS.nombre2%TYPE,
E_apellido EMPLEADOS.apellido%TYPE,
E_apellido2 EMPLEADOS.apellido2%TYPE)
IS
BEGIN
    INSERT INTO EMPLEADOS(cedula_admin, cedula, nombre, nombre2, apellido, apellido2) 
    VALUES (E_cedula_A, E_cedula, E_nombre, E_nombre2, E_apellido, E_apellido2);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_ESCOGIDOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_ESCOGIDOS" (RE_cedula_admin ADMINS.cedula%TYPE,
RE_cedula_empleado EMPLEADOS.cedula%TYPE,
RE_cantidad REGESCOGIDOS.cantidad%TYPE,
RE_fecha REGESCOGIDOS.fecha%TYPE)
IS
BEGIN
    INSERT INTO REGESCOGIDOS(cedula_admin, cedula_empleado, cantidad, fecha)
    VALUES (RE_cedula_admin, RE_cedula_empleado, RE_cantidad, RE_fecha);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_NOMINA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_NOMINA" (
N_cedula_empleado NOMINAS.cedula_empleado%TYPE,
N_salario_base NOMINAS.salario_base%TYPE,
N_fecha NOMINAS.fecha%TYPE)
IS
Total_Kilos NUMBER;
Total_Pedidos NUMBER;
SALARIO NUMBER;
Nombre EMPLEADOS.nombre%TYPE;
Apellido EMPLEADOS.apellido%TYPE;
Admins EMPLEADOS.cedula_admin%TYPE;
BEGIN
    SELECT cedula_admin,nombre,apellido INTO admins,Nombre,Apellido FROM empleados
    WHERE N_cedula_empleado = cedula;

    SELECT SUM(cantidad) INTO Total_Kilos FROM regescogidos
    WHERE N_cedula_empleado = cedula_empleado;
    
    IF (Total_Kilos IS NULL) THEN Total_Kilos:=0;
    END IF;

    SELECT SUM(f.total) INTO Total_Pedidos FROM FACTURA_PEDIDOS f
    JOIN DETALLE_PEDIDOS d on (f.id_pedido = d.id_pedido)
    WHERE N_cedula_empleado = d.cedula_empleado;
    
    IF (Total_Pedidos IS NULL) THEN TOTAL_PEDIDOS:=0;
    END IF;

    SALARIO := (Total_Kilos * N_salario_base ) - Total_Pedidos;

    INSERT INTO NOMINAS (cedula_empleado,cedula_admin ,nombre ,apellido ,total_kilos ,total_pedidos,salario_base,total_pagar,fecha)
    VALUES(N_cedula_empleado,admins,Nombre,Apellido,Total_Kilos,Total_Pedidos,N_salario_base,SALARIO,N_fecha );
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_PEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_PEDIDO" (FP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
FP_fecha  FACTURA_PEDIDOS.fecha%TYPE)
IS
BEGIN
    INSERT INTO FACTURA_PEDIDOS(id_pedido, fecha) 
    VALUES (FP_id_pedido, FP_fecha);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_REGCAFES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_REGCAFES" (RC_cedula_admin ADMINS.cedula%TYPE,
RC_cereza_kilos REGCAFES.cereza_kilos%TYPE,
RC_secos_kilos REGCAFES.secos_kilos%TYPE)
IS
BEGIN
    INSERT INTO REGCAFES (cedula_admin, cereza_kilos, secos_kilos) VALUES (RC_cedula_admin, RC_cereza_kilos, RC_secos_kilos);
END;


/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_VENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."INSERTAR_VENTA" (FV_id_venta FACTURA_VENTAS.id_venta%TYPE,
FV_nombre_empresa FACTURA_VENTAS.nombre_empresa%TYPE,
FV_fecha FACTURA_VENTAS.fecha%TYPE)
IS
BEGIN
    INSERT INTO FACTURA_VENTAS (id_venta, nombre_empresa, fecha) 
    VALUES(FV_id_venta, FV_nombre_empresa, FV_fecha) ;
END;


/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."MODIFICAR_EMPLEADO" (E_cedula EMPLEADOS.cedula%TYPE,
E_nombre EMPLEADOS.nombre%TYPE,
E_nombre2 EMPLEADOS.nombre2%TYPE,
E_apellido EMPLEADOS.apellido%TYPE,
E_apellido2 EMPLEADOS.apellido2%TYPE)
IS
BEGIN
    UPDATE EMPLEADOS
    SET nombre = E_nombre, nombre2 = E_nombre2, apellido = E_apellido, apellido2 = E_apellido2 
    WHERE EMPLEADOS.cedula = E_cedula;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_ESCOGIDOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."MODIFICAR_ESCOGIDOS" (RE_id_escogido REGESCOGIDOS.id_escogido%TYPE,
RE_cedula_empleado EMPLEADOS.cedula%TYPE,
RE_cantidad REGESCOGIDOS.cantidad%TYPE,
RE_fecha REGESCOGIDOS.fecha%TYPE)
IS
BEGIN   
    UPDATE REGESCOGIDOS
    SET cedula_empleado = RE_cedula_empleado, cantidad = RE_cantidad, fecha = RE_fecha
    WHERE id_escogido = RE_id_escogido;
END;


/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_PEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."MODIFICAR_PEDIDO" (FP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
FP_fecha  FACTURA_PEDIDOS.fecha%TYPE)
IS
BEGIN
    UPDATE FACTURA_PEDIDOS
    SET fecha = FP_fecha
    WHERE id_pedido = FP_id_pedido;
END;


/
--------------------------------------------------------
--  DDL for Procedure MODIFICAR_REGCAFES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "PROYECTO"."MODIFICAR_REGCAFES" (RC_id_rcafe REGCAFES.id_rcafe%TYPE,
RC_cereza_kilos REGCAFES.cereza_kilos%TYPE,
RC_secos_kilos REGCAFES.secos_kilos%TYPE,
RC_fecha REGCAFES.fecha%TYPE)
IS
BEGIN
    UPDATE REGCAFES
    SET cereza_kilos = RC_cereza_kilos, secos_kilos = RC_secos_kilos
    WHERE id_rcafe = RC_id_rcafe;
END;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_ADMINISTRADOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_ADMINISTRADOR" 
AS
PROCEDURE insertar_administrador (A_cedula ADMINS.cedula%TYPE,
A_nombre ADMINS.nombre%TYPE,
A_nombre2 ADMINS.nombre2%TYPE,
A_apellido ADMINS.apellido%TYPE,
A_apellido2 ADMINS.apellido2%TYPE,
A_contraseña ADMINS.contraseña%TYPE);
END PK_proce_administrador;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_DPEDIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_DPEDIDO" 
AS
PROCEDURE insertar_detalleP (DP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
DP_id_producto PRODUCTOS.id_producto%TYPE,
DP_cedula_empleado EMPLEADOS.cedula%TYPE,
DP_cantidad DETALLE_PEDIDOS.cantidad%TYPE);
END PK_proce_Dpedido;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_EMPLEADO" 
AS
PROCEDURE insertar_empleado (E_cedula_A ADMINS.cedula%TYPE,
E_cedula EMPLEADOS.cedula%TYPE,
E_nombre EMPLEADOS.nombre%TYPE,
E_nombre2 EMPLEADOS.nombre2%TYPE,
E_apellido EMPLEADOS.apellido%TYPE,
E_apellido2 EMPLEADOS.apellido2%TYPE);

PROCEDURE modificar_empleado(E_cedula EMPLEADOS.cedula%TYPE,
E_nombre EMPLEADOS.nombre%TYPE,
E_nombre2 EMPLEADOS.nombre2%TYPE,
E_apellido EMPLEADOS.apellido%TYPE,
E_apellido2 EMPLEADOS.apellido2%TYPE);

PROCEDURE eliminar_empleado(E_cedula EMPLEADOS.cedula%TYPE);
END PK_proce_empleado;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_FDVENTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_FDVENTA" 
AS
PROCEDURE insertar_detalleV(DFV_cedula_admin DETALLE_FACTURA_VENTAS.cedula_admin%TYPE,
DFV_id_venta DETALLE_FACTURA_VENTAS.id_venta%TYPE,
DFV_id_cafe DETALLE_FACTURA_VENTAS.id_cafe%TYPE,
DFV_id_tipoC DETALLE_FACTURA_VENTAS.id_tipoC%TYPE,
DFV_factor DETALLE_FACTURA_VENTAS.factor%TYPE,
DFV_kilos_netos DETALLE_FACTURA_VENTAS.kilos_netos%TYPE,
DFV_valor_Kilo DETALLE_FACTURA_VENTAS.valor_Kilo%TYPE,
DFV_valor_baseKilo DETALLE_FACTURA_VENTAS.valor_baseKilo%TYPE);
END PK_proce_FDventa;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_FVENTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_FVENTA" 
AS
PROCEDURE insertar_venta(FV_id_venta FACTURA_VENTAS.id_venta%TYPE,
FV_nombre_empresa FACTURA_VENTAS.nombre_empresa%TYPE,
FV_fecha FACTURA_VENTAS.fecha%TYPE);
END PK_proce_Fventa; 


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_NOMINA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_NOMINA" 
AS
PROCEDURE insertar_nomina(
N_cedula_empleado NOMINAS.cedula_empleado%TYPE,
N_salario_base NOMINAS.salario_base%TYPE,
N_fecha NOMINAS.fecha%TYPE);
END PK_proce_nomina;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_PEDIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_PEDIDO" 
AS
PROCEDURE insertar_pedido(FP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
FP_fecha  FACTURA_PEDIDOS.fecha%TYPE);

PROCEDURE modificar_pedido(FP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
FP_fecha  FACTURA_PEDIDOS.fecha%TYPE);
END PK_proce_pedido;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_REGCAFE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_REGCAFE" 
AS
PROCEDURE insertar_regcafes(RC_cedula_admin ADMINS.cedula%TYPE,
RC_cereza_kilos REGCAFES.cereza_kilos%TYPE,
RC_secos_kilos REGCAFES.secos_kilos%TYPE);

PROCEDURE modificar_regcafes(RC_id_rcafe REGCAFES.id_rcafe%TYPE,
RC_cereza_kilos REGCAFES.cereza_kilos%TYPE,
RC_secos_kilos REGCAFES.secos_kilos%TYPE,
RC_fecha REGCAFES.fecha%TYPE);
END PK_proce_regcafe;


/
--------------------------------------------------------
--  DDL for Package PK_PROCE_REGESCOGIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "PROYECTO"."PK_PROCE_REGESCOGIDO" 
AS
PROCEDURE insertar_escogidos (RE_cedula_admin ADMINS.cedula%TYPE,
RE_cedula_empleado EMPLEADOS.cedula%TYPE,
RE_cantidad REGESCOGIDOS.cantidad%TYPE,
RE_fecha REGESCOGIDOS.fecha%TYPE);

PROCEDURE modificar_escogidos (RE_id_escogido REGESCOGIDOS.id_escogido%TYPE,
RE_cedula_empleado EMPLEADOS.cedula%TYPE,
RE_cantidad REGESCOGIDOS.cantidad%TYPE,
RE_fecha REGESCOGIDOS.fecha%TYPE);
END PK_proce_regescogido;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_ADMINISTRADOR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_ADMINISTRADOR" 
AS
PROCEDURE insertar_administrador (A_cedula ADMINS.cedula%TYPE,
A_nombre ADMINS.nombre%TYPE,
A_nombre2 ADMINS.nombre2%TYPE,
A_apellido ADMINS.apellido%TYPE,
A_apellido2 ADMINS.apellido2%TYPE,
A_contraseña ADMINS.contraseña%TYPE)
IS
BEGIN
    INSERT INTO ADMINS(cedula, nombre, nombre2, apellido, apellido2, contraseña) 
    VALUES (A_cedula, A_nombre, A_nombre2, A_apellido, A_apellido2, A_contraseña);
END;
END  PK_proce_administrador;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_DPEDIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_DPEDIDO" 
AS
PROCEDURE insertar_detalleP (DP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
DP_id_producto PRODUCTOS.id_producto%TYPE,
DP_cedula_empleado EMPLEADOS.cedula%TYPE,
DP_cantidad DETALLE_PEDIDOS.cantidad%TYPE)
IS
BEGIN
    INSERT INTO DETALLE_PEDIDOS(id_pedido, id_producto, cedula_empleado, cantidad) 
    VALUES (DP_id_pedido, DP_id_producto, DP_cedula_empleado, DP_cantidad);
END;
END PK_proce_Dpedido;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_EMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_EMPLEADO" 
AS
PROCEDURE insertar_empleado (E_cedula_A ADMINS.cedula%TYPE,
E_cedula EMPLEADOS.cedula%TYPE,
E_nombre EMPLEADOS.nombre%TYPE,
E_nombre2 EMPLEADOS.nombre2%TYPE,
E_apellido EMPLEADOS.apellido%TYPE,
E_apellido2 EMPLEADOS.apellido2%TYPE)
IS
BEGIN
    INSERT INTO EMPLEADOS(cedula_admin, cedula, nombre, nombre2, apellido, apellido2) 
    VALUES (E_cedula_A, E_cedula, E_nombre, E_nombre2, E_apellido, E_apellido2);
END;

PROCEDURE modificar_empleado(E_cedula EMPLEADOS.cedula%TYPE,
E_nombre EMPLEADOS.nombre%TYPE,
E_nombre2 EMPLEADOS.nombre2%TYPE,
E_apellido EMPLEADOS.apellido%TYPE,
E_apellido2 EMPLEADOS.apellido2%TYPE)
IS
BEGIN
    UPDATE EMPLEADOS
    SET nombre = E_nombre, nombre2 = E_nombre2, apellido = E_apellido2, apellido2 = E_apellido2 
    WHERE EMPLEADOS.cedula = E_cedula;
END;

PROCEDURE eliminar_empleado(E_cedula EMPLEADOS.cedula%TYPE)
IS
BEGIN
    DELETE 
    FROM EMPLEADOS
    WHERE  EMPLEADOS.cedula = E_cedula;
END;
END PK_proce_empleado;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_FDVENTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_FDVENTA" 
AS
PROCEDURE insertar_detalleV(DFV_cedula_admin DETALLE_FACTURA_VENTAS.cedula_admin%TYPE,
DFV_id_venta DETALLE_FACTURA_VENTAS.id_venta%TYPE,
DFV_id_cafe DETALLE_FACTURA_VENTAS.id_cafe%TYPE,
DFV_id_tipoC DETALLE_FACTURA_VENTAS.id_tipoC%TYPE,
DFV_factor DETALLE_FACTURA_VENTAS.factor%TYPE,
DFV_kilos_netos DETALLE_FACTURA_VENTAS.kilos_netos%TYPE,
DFV_valor_Kilo DETALLE_FACTURA_VENTAS.valor_Kilo%TYPE,
DFV_valor_baseKilo DETALLE_FACTURA_VENTAS.valor_baseKilo%TYPE)
IS
BEGIN
    INSERT INTO DETALLE_FACTURA_VENTAS(cedula_admin, id_venta,id_cafe, id_tipoC, factor, kilos_netos, valor_Kilo, valor_baseKilo) 
    VALUES (DFV_cedula_admin, DFV_id_venta, DFV_id_cafe, DFV_id_tipoC, DFV_factor, DFV_kilos_netos, DFV_valor_Kilo, DFV_valor_baseKilo);
END;
END PK_proce_FDventa;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_FVENTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_FVENTA" 
AS
PROCEDURE insertar_venta(FV_id_venta FACTURA_VENTAS.id_venta%TYPE,
FV_nombre_empresa FACTURA_VENTAS.nombre_empresa%TYPE,
FV_fecha FACTURA_VENTAS.fecha%TYPE)
IS
BEGIN
    INSERT INTO FACTURA_VENTAS (id_venta, nombre_empresa, fecha) 
    VALUES(FV_id_venta, FV_nombre_empresa, FV_fecha) ;
END;
END  PK_proce_Fventa;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_NOMINA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_NOMINA" 
AS
PROCEDURE insertar_nomina(
N_cedula_empleado NOMINAS.cedula_empleado%TYPE,
N_salario_base NOMINAS.salario_base%TYPE,
N_fecha NOMINAS.fecha%TYPE)
IS
Total_Kilos NUMBER;
Total_Pedidos NUMBER;
SALARIO NUMBER;
Nombre EMPLEADOS.nombre%TYPE;
Apellido EMPLEADOS.apellido%TYPE;
Admins EMPLEADOS.cedula_admin%TYPE;
BEGIN
    SELECT cedula_admin,nombre,apellido INTO admins,Nombre,Apellido FROM empleados
    WHERE N_cedula_empleado = cedula;

    SELECT SUM(cantidad) INTO Total_Kilos FROM regescogidos
    WHERE N_cedula_empleado = cedula_empleado;

    SELECT SUM(f.total) INTO Total_Pedidos FROM FACTURA_PEDIDOS f
    JOIN DETALLE_PEDIDOS d on (f.id_pedido = d.id_pedido)
    WHERE N_cedula_empleado = d.cedula_empleado;

    SALARIO := (Total_Kilos * N_salario_base ) - Total_Pedidos;

    INSERT INTO NOMINAS (cedula_empleado,cedula_admin ,nombre ,apellido ,total_kilos ,total_pedidos,salario_base,total_pagar,fecha)
    VALUES(N_cedula_empleado,admins,Nombre,Apellido,Total_Kilos,Total_Pedidos,N_salario_base,SALARIO,N_fecha );
END;
END  PK_proce_nomina;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_PEDIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_PEDIDO" 
AS
PROCEDURE insertar_pedido(FP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
FP_fecha  FACTURA_PEDIDOS.fecha%TYPE)
IS
BEGIN
    INSERT INTO FACTURA_PEDIDOS(id_pedido, fecha) 
    VALUES (FP_id_pedido, FP_fecha);
END;

PROCEDURE modificar_pedido(FP_id_pedido FACTURA_PEDIDOS.id_pedido%TYPE,
FP_fecha  FACTURA_PEDIDOS.fecha%TYPE)
IS
BEGIN
    UPDATE FACTURA_PEDIDOS
    SET fecha = FP_fecha
    WHERE id_pedido = FP_id_pedido;
END;
END  PK_proce_pedido;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_REGCAFE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_REGCAFE" 
AS
PROCEDURE insertar_regcafes(RC_cedula_admin ADMINS.cedula%TYPE,
RC_cereza_kilos REGCAFES.cereza_kilos%TYPE,
RC_secos_kilos REGCAFES.secos_kilos%TYPE)
IS
BEGIN
    INSERT INTO REGCAFES (cedula_admin, cereza_kilos, secos_kilos) VALUES (RC_cedula_admin, RC_cereza_kilos, RC_secos_kilos);
END;

PROCEDURE modificar_regcafes(RC_id_rcafe REGCAFES.id_rcafe%TYPE,
RC_cereza_kilos REGCAFES.cereza_kilos%TYPE,
RC_secos_kilos REGCAFES.secos_kilos%TYPE,
RC_fecha REGCAFES.fecha%TYPE)
IS
BEGIN
    UPDATE REGCAFES
    SET cereza_kilos = RC_cereza_kilos, secos_kilos = RC_secos_kilos
    WHERE id_rcafe = RC_id_rcafe;
END;
END PK_proce_regcafe;


/
--------------------------------------------------------
--  DDL for Package Body PK_PROCE_REGESCOGIDO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "PROYECTO"."PK_PROCE_REGESCOGIDO" 
AS
 PROCEDURE insertar_escogidos (RE_cedula_admin ADMINS.cedula%TYPE,
RE_cedula_empleado EMPLEADOS.cedula%TYPE,
RE_cantidad REGESCOGIDOS.cantidad%TYPE,
RE_fecha REGESCOGIDOS.fecha%TYPE)
IS
BEGIN
    INSERT INTO REGESCOGIDOS(cedula_admin, cedula_empleado, cantidad, fecha)
    VALUES (RE_cedula_admin, RE_cedula_empleado, RE_cantidad, RE_fecha);
END;

PROCEDURE modificar_escogidos (RE_id_escogido REGESCOGIDOS.id_escogido%TYPE,
RE_cedula_empleado EMPLEADOS.cedula%TYPE,
RE_cantidad REGESCOGIDOS.cantidad%TYPE,
RE_fecha REGESCOGIDOS.fecha%TYPE)
IS
BEGIN   
    UPDATE REGESCOGIDOS
    SET cedula_empleado = RE_cedula_empleado, cantidad = RE_cantidad, fecha = RE_fecha
    WHERE id_escogido = RE_id_escogido;
END;
END PK_proce_regescogido;


/
--------------------------------------------------------
--  DDL for Function EXISTEEMPLEADO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "PROYECTO"."EXISTEEMPLEADO" (CedulaP varchar) return VARCHAR IS
EXISTE NUMBER;
BEGIN
SELECT COUNT(CEDULA) INTO EXISTE FROM EMPLEADOS WHERE Cedula=Cedulap;

 IF (EXISTE=0) THEN RETURN 'N';
   ELSE
     RETURN 'S';
  END IF;

END;

/
--------------------------------------------------------
--  Constraints for Table ADMINS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."ADMINS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."ADMINS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."ADMINS" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."ADMINS" ADD CONSTRAINT "PK_ADMINS_CEDULA" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."EMPLEADOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."EMPLEADOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "PROYECTO"."EMPLEADOS" ADD CONSTRAINT "PK_EMPLEADOS_CEDULA" PRIMARY KEY ("CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."PRODUCTOS" ADD CONSTRAINT "PK_PRODUCTOS_ID_PRODUCTO" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA_PEDIDOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."FACTURA_PEDIDOS" ADD CONSTRAINT "PK_PEDIDOS_ID_PEDIDO" PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOS_CAFES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."TIPOS_CAFES" ADD CONSTRAINT "PK_TIPOS_CAFES_ID_TIPOCAFE" PRIMARY KEY ("ID_TIPOCAFE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOMINAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."NOMINAS" ADD CONSTRAINT "PK_NOMINAS_ID_NOMINA" PRIMARY KEY ("ID_NOMINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_FACTURA_VENTAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DETALLE_FACTURA_VENTAS" ADD CONSTRAINT "UK_DETALLE_FACTURA_VENTAS" UNIQUE ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAFES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."CAFES" ADD CONSTRAINT "PK_CAFES_ID_CAFE" PRIMARY KEY ("ID_CAFE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGCAFES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."REGCAFES" ADD CONSTRAINT "PK_CAFES_ID_RCAFE" PRIMARY KEY ("ID_RCAFE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA_VENTAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."FACTURA_VENTAS" ADD CONSTRAINT "PK_VENTAS_ID_VENTA" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PROYECTO"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_FACTURA_VENTAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DETALLE_FACTURA_VENTAS" ADD CONSTRAINT "FK_FACTURA_VENTAS_ID_VENTA" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "PROYECTO"."FACTURA_VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "PROYECTO"."DETALLE_FACTURA_VENTAS" ADD CONSTRAINT "FK_ADMINS_CEDULA_ADMIN" FOREIGN KEY ("CEDULA_ADMIN")
	  REFERENCES "PROYECTO"."ADMINS" ("CEDULA") ENABLE;
  ALTER TABLE "PROYECTO"."DETALLE_FACTURA_VENTAS" ADD CONSTRAINT "FK_TIPOCAFE_TIPO_CAFE" FOREIGN KEY ("ID_TIPOC")
	  REFERENCES "PROYECTO"."TIPOS_CAFES" ("ID_TIPOCAFE") ENABLE;
  ALTER TABLE "PROYECTO"."DETALLE_FACTURA_VENTAS" ADD CONSTRAINT "FK_CAFES_ID_CAFE" FOREIGN KEY ("ID_CAFE")
	  REFERENCES "PROYECTO"."CAFES" ("ID_CAFE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_PEDIDOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."DETALLE_PEDIDOS" ADD CONSTRAINT "FK_EMPLEADO_PEDIDOS_ID_PEDIDO" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "PROYECTO"."FACTURA_PEDIDOS" ("ID_PEDIDO") ENABLE;
  ALTER TABLE "PROYECTO"."DETALLE_PEDIDOS" ADD CONSTRAINT "FK_EMPLEADO_PEDIDOS_CEDULA_EMPLEADO" FOREIGN KEY ("CEDULA_EMPLEADO")
	  REFERENCES "PROYECTO"."EMPLEADOS" ("CEDULA") ENABLE;
  ALTER TABLE "PROYECTO"."DETALLE_PEDIDOS" ADD CONSTRAINT "FK_PRODUCTOS_PEDIDOS_ID_PRODUCTO" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "PROYECTO"."PRODUCTOS" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."EMPLEADOS" ADD CONSTRAINT "FK_EMPLEADOS_CEDULA_ADMIN" FOREIGN KEY ("CEDULA_ADMIN")
	  REFERENCES "PROYECTO"."ADMINS" ("CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOMINAS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."NOMINAS" ADD CONSTRAINT "FK_NOMINAS_CEDULA_ADMIN" FOREIGN KEY ("CEDULA_ADMIN")
	  REFERENCES "PROYECTO"."ADMINS" ("CEDULA") ENABLE;
  ALTER TABLE "PROYECTO"."NOMINAS" ADD CONSTRAINT "FK_NOMINAS_CEDULA_EMPLEADO" FOREIGN KEY ("CEDULA_EMPLEADO")
	  REFERENCES "PROYECTO"."EMPLEADOS" ("CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGCAFES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."REGCAFES" ADD CONSTRAINT "FK_REGCAFES_CEDULA_ADMIN" FOREIGN KEY ("CEDULA_ADMIN")
	  REFERENCES "PROYECTO"."ADMINS" ("CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGESCOGIDOS
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."REGESCOGIDOS" ADD CONSTRAINT "FK_REGESCOGIDOS_CEDULA_ADMIN" FOREIGN KEY ("CEDULA_ADMIN")
	  REFERENCES "PROYECTO"."ADMINS" ("CEDULA") ENABLE;
  ALTER TABLE "PROYECTO"."REGESCOGIDOS" ADD CONSTRAINT "FK_REGESCOGIDOS_CEDULA_EMPLEADO" FOREIGN KEY ("CEDULA_EMPLEADO")
	  REFERENCES "PROYECTO"."EMPLEADOS" ("CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TIPOS_CAFES
--------------------------------------------------------

  ALTER TABLE "PROYECTO"."TIPOS_CAFES" ADD CONSTRAINT "FK_REGCAFES_ID_CAFE" FOREIGN KEY ("ID_CAFE")
	  REFERENCES "PROYECTO"."CAFES" ("ID_CAFE") ENABLE;
